// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameServer struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Address       string                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Game          string                   `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Name          string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Info          string                   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"` // optional extra info
	Capabilities  *GameServer_Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxPlayers    uint32                   `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	OnlinePlayers uint32                   `protobuf:"varint,7,opt,name=online_players,json=onlinePlayers,proto3" json:"online_players,omitempty"`
	Players       []*GameServer_Player     `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *GameServer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GameServer) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GameServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *GameServer) GetCapabilities() *GameServer_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GameServer) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameServer) GetOnlinePlayers() uint32 {
	if x != nil {
		return x.OnlinePlayers
	}
	return 0
}

func (x *GameServer) GetPlayers() []*GameServer_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type GameServers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameServer    []*GameServer          `protobuf:"bytes,1,rep,name=gameServer,proto3" json:"gameServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServers) Reset() {
	*x = GameServers{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServers) ProtoMessage() {}

func (x *GameServers) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServers.ProtoReflect.Descriptor instead.
func (*GameServers) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *GameServers) GetGameServer() []*GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

type GameServer_Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   bool                   `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	PlayerNames   bool                   `protobuf:"varint,2,opt,name=player_names,json=playerNames,proto3" json:"player_names,omitempty"`
	PlayerScore   bool                   `protobuf:"varint,3,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Capabilities) Reset() {
	*x = GameServer_Capabilities{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Capabilities) ProtoMessage() {}

func (x *GameServer_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Capabilities.ProtoReflect.Descriptor instead.
func (*GameServer_Capabilities) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GameServer_Capabilities) GetPlayerCount() bool {
	if x != nil {
		return x.PlayerCount
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerNames() bool {
	if x != nil {
		return x.PlayerNames
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerScore() bool {
	if x != nil {
		return x.PlayerScore
	}
	return false
}

type GameServer_Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"` // optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Player) Reset() {
	*x = GameServer_Player{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Player) ProtoMessage() {}

func (x *GameServer_Player) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Player.ProtoReflect.Descriptor instead.
func (*GameServer_Player) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GameServer_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer_Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameServer_Player) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\n" +
	"projectile\"\xed\x03\n" +
	"\n" +
	"GameServer\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\x12G\n" +
	"\fcapabilities\x18\x05 \x01(\v2#.projectile.GameServer.CapabilitiesR\fcapabilities\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\rR\n" +
	"maxPlayers\x12%\n" +
	"\x0eonline_players\x18\a \x01(\rR\ronlinePlayers\x127\n" +
	"\aplayers\x18\b \x03(\v2\x1d.projectile.GameServer.PlayerR\aplayers\x1aw\n" +
	"\fCapabilities\x12!\n" +
	"\fplayer_count\x18\x01 \x01(\bR\vplayerCount\x12!\n" +
	"\fplayer_names\x18\x02 \x01(\bR\vplayerNames\x12!\n" +
	"\fplayer_score\x18\x03 \x01(\bR\vplayerScore\x1aF\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\"E\n" +
	"\vGameServers\x126\n" +
	"\n" +
	"gameServer\x18\x01 \x03(\v2\x16.projectile.GameServerR\n" +
	"gameServerB/Z-github.com/Ctrl-Alt-GG/projectile/model;modelb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_proto_goTypes = []any{
	(*GameServer)(nil),              // 0: projectile.GameServer
	(*GameServers)(nil),             // 1: projectile.GameServers
	(*GameServer_Capabilities)(nil), // 2: projectile.GameServer.Capabilities
	(*GameServer_Player)(nil),       // 3: projectile.GameServer.Player
}
var file_model_proto_depIdxs = []int32{
	2, // 0: projectile.GameServer.capabilities:type_name -> projectile.GameServer.Capabilities
	3, // 1: projectile.GameServer.players:type_name -> projectile.GameServer.Player
	0, // 2: projectile.GameServers.gameServer:type_name -> projectile.GameServer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
