// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: agentmsg.proto

package agentmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameServer struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Game               string                   `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Name               string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addresses          []string                 `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Info               *string                  `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"` // optional extra info
	Capabilities       *GameServer_Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxPlayers         uint32                   `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	OnlinePlayersCount *uint32                  `protobuf:"varint,7,opt,name=online_players_count,json=onlinePlayersCount,proto3,oneof" json:"online_players_count,omitempty"`
	OnlinePlayers      []*GameServer_Player     `protobuf:"bytes,8,rep,name=online_players,json=onlinePlayers,proto3" json:"online_players,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_agentmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{0}
}

func (x *GameServer) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GameServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GameServer) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

func (x *GameServer) GetCapabilities() *GameServer_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GameServer) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameServer) GetOnlinePlayersCount() uint32 {
	if x != nil && x.OnlinePlayersCount != nil {
		return *x.OnlinePlayersCount
	}
	return 0
}

func (x *GameServer) GetOnlinePlayers() []*GameServer_Player {
	if x != nil {
		return x.OnlinePlayers
	}
	return nil
}

type GameServer_Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   bool                   `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	PlayerNames   bool                   `protobuf:"varint,2,opt,name=player_names,json=playerNames,proto3" json:"player_names,omitempty"`
	PlayerScore   bool                   `protobuf:"varint,3,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	PlayerTeam    bool                   `protobuf:"varint,4,opt,name=player_team,json=playerTeam,proto3" json:"player_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Capabilities) Reset() {
	*x = GameServer_Capabilities{}
	mi := &file_agentmsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Capabilities) ProtoMessage() {}

func (x *GameServer_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Capabilities.ProtoReflect.Descriptor instead.
func (*GameServer_Capabilities) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GameServer_Capabilities) GetPlayerCount() bool {
	if x != nil {
		return x.PlayerCount
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerNames() bool {
	if x != nil {
		return x.PlayerNames
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerScore() bool {
	if x != nil {
		return x.PlayerScore
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerTeam() bool {
	if x != nil {
		return x.PlayerTeam
	}
	return false
}

type GameServer_Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         *int32                 `protobuf:"varint,2,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Team          *string                `protobuf:"bytes,3,opt,name=team,proto3,oneof" json:"team,omitempty"`
	Info          *string                `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"` // optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Player) Reset() {
	*x = GameServer_Player{}
	mi := &file_agentmsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Player) ProtoMessage() {}

func (x *GameServer_Player) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Player.ProtoReflect.Descriptor instead.
func (*GameServer_Player) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GameServer_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer_Player) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *GameServer_Player) GetTeam() string {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return ""
}

func (x *GameServer_Player) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

var File_agentmsg_proto protoreflect.FileDescriptor

const file_agentmsg_proto_rawDesc = "" +
	"\n" +
	"\x0eagentmsg.proto\x12\n" +
	"projectile\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x05\n" +
	"\n" +
	"GameServer\x12\x12\n" +
	"\x04game\x18\x01 \x01(\tR\x04game\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x17\n" +
	"\x04info\x18\x04 \x01(\tH\x00R\x04info\x88\x01\x01\x12G\n" +
	"\fcapabilities\x18\x05 \x01(\v2#.projectile.GameServer.CapabilitiesR\fcapabilities\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\rR\n" +
	"maxPlayers\x125\n" +
	"\x14online_players_count\x18\a \x01(\rH\x01R\x12onlinePlayersCount\x88\x01\x01\x12D\n" +
	"\x0eonline_players\x18\b \x03(\v2\x1d.projectile.GameServer.PlayerR\ronlinePlayers\x1a\x98\x01\n" +
	"\fCapabilities\x12!\n" +
	"\fplayer_count\x18\x01 \x01(\bR\vplayerCount\x12!\n" +
	"\fplayer_names\x18\x02 \x01(\bR\vplayerNames\x12!\n" +
	"\fplayer_score\x18\x03 \x01(\bR\vplayerScore\x12\x1f\n" +
	"\vplayer_team\x18\x04 \x01(\bR\n" +
	"playerTeam\x1a\x85\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05score\x18\x02 \x01(\x05H\x00R\x05score\x88\x01\x01\x12\x17\n" +
	"\x04team\x18\x03 \x01(\tH\x01R\x04team\x88\x01\x01\x12\x17\n" +
	"\x04info\x18\x04 \x01(\tH\x02R\x04info\x88\x01\x01B\b\n" +
	"\x06_scoreB\a\n" +
	"\x05_teamB\a\n" +
	"\x05_infoB\a\n" +
	"\x05_infoB\x17\n" +
	"\x15_online_players_count2\x8a\x01\n" +
	"\vGameServers\x12=\n" +
	"\aUpdates\x12\x16.projectile.GameServer\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12<\n" +
	"\bWithdraw\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B9Z7github.com/Ctrl-Alt-GG/projectile/pkg/agentmsg;agentmsgb\x06proto3"

var (
	file_agentmsg_proto_rawDescOnce sync.Once
	file_agentmsg_proto_rawDescData []byte
)

func file_agentmsg_proto_rawDescGZIP() []byte {
	file_agentmsg_proto_rawDescOnce.Do(func() {
		file_agentmsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentmsg_proto_rawDesc), len(file_agentmsg_proto_rawDesc)))
	})
	return file_agentmsg_proto_rawDescData
}

var file_agentmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agentmsg_proto_goTypes = []any{
	(*GameServer)(nil),              // 0: projectile.GameServer
	(*GameServer_Capabilities)(nil), // 1: projectile.GameServer.Capabilities
	(*GameServer_Player)(nil),       // 2: projectile.GameServer.Player
	(*emptypb.Empty)(nil),           // 3: google.protobuf.Empty
}
var file_agentmsg_proto_depIdxs = []int32{
	1, // 0: projectile.GameServer.capabilities:type_name -> projectile.GameServer.Capabilities
	2, // 1: projectile.GameServer.online_players:type_name -> projectile.GameServer.Player
	0, // 2: projectile.GameServers.Updates:input_type -> projectile.GameServer
	3, // 3: projectile.GameServers.Withdraw:input_type -> google.protobuf.Empty
	3, // 4: projectile.GameServers.Updates:output_type -> google.protobuf.Empty
	3, // 5: projectile.GameServers.Withdraw:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agentmsg_proto_init() }
func file_agentmsg_proto_init() {
	if File_agentmsg_proto != nil {
		return
	}
	file_agentmsg_proto_msgTypes[0].OneofWrappers = []any{}
	file_agentmsg_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentmsg_proto_rawDesc), len(file_agentmsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentmsg_proto_goTypes,
		DependencyIndexes: file_agentmsg_proto_depIdxs,
		MessageInfos:      file_agentmsg_proto_msgTypes,
	}.Build()
	File_agentmsg_proto = out.File
	file_agentmsg_proto_goTypes = nil
	file_agentmsg_proto_depIdxs = nil
}
