// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: agentmsg.proto

package agentmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_HAPPY   ErrorType = 0 // i.e.: no errors
	ErrorType_CLOSING ErrorType = 1
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "HAPPY",
		1: "CLOSING",
	}
	ErrorType_value = map[string]int32{
		"HAPPY":   0,
		"CLOSING": 1,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_agentmsg_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_agentmsg_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ErrorType              `protobuf:"varint,1,opt,name=type,proto3,enum=projectile.ErrorType" json:"type,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=Message,proto3,oneof" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agentmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_HAPPY
}

func (x *Error) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Game          string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_agentmsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{1}
}

func (x *Identifier) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Identifier) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type GameServer struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Id                 *Identifier              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AlternateAddresses []string                 `protobuf:"bytes,3,rep,name=alternate_addresses,json=alternateAddresses,proto3" json:"alternate_addresses,omitempty"`
	Info               *string                  `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"` // optional extra info
	Capabilities       *GameServer_Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxPlayers         uint32                   `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	OnlinePlayersCount *uint32                  `protobuf:"varint,7,opt,name=online_players_count,json=onlinePlayersCount,proto3,oneof" json:"online_players_count,omitempty"`
	OnlinePlayers      []*GameServer_Player     `protobuf:"bytes,8,rep,name=online_players,json=onlinePlayers,proto3" json:"online_players,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	mi := &file_agentmsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{2}
}

func (x *GameServer) GetId() *Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GameServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer) GetAlternateAddresses() []string {
	if x != nil {
		return x.AlternateAddresses
	}
	return nil
}

func (x *GameServer) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

func (x *GameServer) GetCapabilities() *GameServer_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GameServer) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameServer) GetOnlinePlayersCount() uint32 {
	if x != nil && x.OnlinePlayersCount != nil {
		return *x.OnlinePlayersCount
	}
	return 0
}

func (x *GameServer) GetOnlinePlayers() []*GameServer_Player {
	if x != nil {
		return x.OnlinePlayers
	}
	return nil
}

type GameServer_Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount   bool                   `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	PlayerNames   bool                   `protobuf:"varint,2,opt,name=player_names,json=playerNames,proto3" json:"player_names,omitempty"`
	PlayerScore   bool                   `protobuf:"varint,3,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	PlayerTeam    bool                   `protobuf:"varint,4,opt,name=player_team,json=playerTeam,proto3" json:"player_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Capabilities) Reset() {
	*x = GameServer_Capabilities{}
	mi := &file_agentmsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Capabilities) ProtoMessage() {}

func (x *GameServer_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Capabilities.ProtoReflect.Descriptor instead.
func (*GameServer_Capabilities) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GameServer_Capabilities) GetPlayerCount() bool {
	if x != nil {
		return x.PlayerCount
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerNames() bool {
	if x != nil {
		return x.PlayerNames
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerScore() bool {
	if x != nil {
		return x.PlayerScore
	}
	return false
}

func (x *GameServer_Capabilities) GetPlayerTeam() bool {
	if x != nil {
		return x.PlayerTeam
	}
	return false
}

type GameServer_Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         *int32                 `protobuf:"varint,2,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Team          *string                `protobuf:"bytes,3,opt,name=team,proto3,oneof" json:"team,omitempty"`
	Info          *string                `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"` // optional extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameServer_Player) Reset() {
	*x = GameServer_Player{}
	mi := &file_agentmsg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameServer_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer_Player) ProtoMessage() {}

func (x *GameServer_Player) ProtoReflect() protoreflect.Message {
	mi := &file_agentmsg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer_Player.ProtoReflect.Descriptor instead.
func (*GameServer_Player) Descriptor() ([]byte, []int) {
	return file_agentmsg_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GameServer_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameServer_Player) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *GameServer_Player) GetTeam() string {
	if x != nil && x.Team != nil {
		return *x.Team
	}
	return ""
}

func (x *GameServer_Player) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

var File_agentmsg_proto protoreflect.FileDescriptor

const file_agentmsg_proto_rawDesc = "" +
	"\n" +
	"\x0eagentmsg.proto\x12\n" +
	"projectile\"]\n" +
	"\x05Error\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.projectile.ErrorTypeR\x04type\x12\x1d\n" +
	"\aMessage\x18\x02 \x01(\tH\x00R\aMessage\x88\x01\x01B\n" +
	"\n" +
	"\b_Message\":\n" +
	"\n" +
	"Identifier\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\"\xbe\x05\n" +
	"\n" +
	"GameServer\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.projectile.IdentifierR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x13alternate_addresses\x18\x03 \x03(\tR\x12alternateAddresses\x12\x17\n" +
	"\x04info\x18\x04 \x01(\tH\x00R\x04info\x88\x01\x01\x12G\n" +
	"\fcapabilities\x18\x05 \x01(\v2#.projectile.GameServer.CapabilitiesR\fcapabilities\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\rR\n" +
	"maxPlayers\x125\n" +
	"\x14online_players_count\x18\a \x01(\rH\x01R\x12onlinePlayersCount\x88\x01\x01\x12D\n" +
	"\x0eonline_players\x18\b \x03(\v2\x1d.projectile.GameServer.PlayerR\ronlinePlayers\x1a\x98\x01\n" +
	"\fCapabilities\x12!\n" +
	"\fplayer_count\x18\x01 \x01(\bR\vplayerCount\x12!\n" +
	"\fplayer_names\x18\x02 \x01(\bR\vplayerNames\x12!\n" +
	"\fplayer_score\x18\x03 \x01(\bR\vplayerScore\x12\x1f\n" +
	"\vplayer_team\x18\x04 \x01(\bR\n" +
	"playerTeam\x1a\x85\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05score\x18\x02 \x01(\x05H\x00R\x05score\x88\x01\x01\x12\x17\n" +
	"\x04team\x18\x03 \x01(\tH\x01R\x04team\x88\x01\x01\x12\x17\n" +
	"\x04info\x18\x04 \x01(\tH\x02R\x04info\x88\x01\x01B\b\n" +
	"\x06_scoreB\a\n" +
	"\x05_teamB\a\n" +
	"\x05_infoB\a\n" +
	"\x05_infoB\x17\n" +
	"\x15_online_players_count*#\n" +
	"\tErrorType\x12\t\n" +
	"\x05HAPPY\x10\x00\x12\v\n" +
	"\aCLOSING\x10\x012\x80\x01\n" +
	"\vGameServers\x128\n" +
	"\aUpdates\x12\x16.projectile.GameServer\x1a\x11.projectile.Error\"\x00(\x01\x127\n" +
	"\bWithdraw\x12\x16.projectile.Identifier\x1a\x11.projectile.Error\"\x00B9Z7github.com/Ctrl-Alt-GG/projectile/pkg/agentmsg;agentmsgb\x06proto3"

var (
	file_agentmsg_proto_rawDescOnce sync.Once
	file_agentmsg_proto_rawDescData []byte
)

func file_agentmsg_proto_rawDescGZIP() []byte {
	file_agentmsg_proto_rawDescOnce.Do(func() {
		file_agentmsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentmsg_proto_rawDesc), len(file_agentmsg_proto_rawDesc)))
	})
	return file_agentmsg_proto_rawDescData
}

var file_agentmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agentmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agentmsg_proto_goTypes = []any{
	(ErrorType)(0),                  // 0: projectile.ErrorType
	(*Error)(nil),                   // 1: projectile.Error
	(*Identifier)(nil),              // 2: projectile.Identifier
	(*GameServer)(nil),              // 3: projectile.GameServer
	(*GameServer_Capabilities)(nil), // 4: projectile.GameServer.Capabilities
	(*GameServer_Player)(nil),       // 5: projectile.GameServer.Player
}
var file_agentmsg_proto_depIdxs = []int32{
	0, // 0: projectile.Error.type:type_name -> projectile.ErrorType
	2, // 1: projectile.GameServer.id:type_name -> projectile.Identifier
	4, // 2: projectile.GameServer.capabilities:type_name -> projectile.GameServer.Capabilities
	5, // 3: projectile.GameServer.online_players:type_name -> projectile.GameServer.Player
	3, // 4: projectile.GameServers.Updates:input_type -> projectile.GameServer
	2, // 5: projectile.GameServers.Withdraw:input_type -> projectile.Identifier
	1, // 6: projectile.GameServers.Updates:output_type -> projectile.Error
	1, // 7: projectile.GameServers.Withdraw:output_type -> projectile.Error
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agentmsg_proto_init() }
func file_agentmsg_proto_init() {
	if File_agentmsg_proto != nil {
		return
	}
	file_agentmsg_proto_msgTypes[0].OneofWrappers = []any{}
	file_agentmsg_proto_msgTypes[2].OneofWrappers = []any{}
	file_agentmsg_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentmsg_proto_rawDesc), len(file_agentmsg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentmsg_proto_goTypes,
		DependencyIndexes: file_agentmsg_proto_depIdxs,
		EnumInfos:         file_agentmsg_proto_enumTypes,
		MessageInfos:      file_agentmsg_proto_msgTypes,
	}.Build()
	File_agentmsg_proto = out.File
	file_agentmsg_proto_goTypes = nil
	file_agentmsg_proto_depIdxs = nil
}
