// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agentmsg.proto

package agentmsg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameServers_Updates_FullMethodName  = "/projectile.GameServers/Updates"
	GameServers_Withdraw_FullMethodName = "/projectile.GameServers/Withdraw"
)

// GameServersClient is the client API for GameServers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServersClient interface {
	Updates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GameServer, emptypb.Empty], error)
	Withdraw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gameServersClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServersClient(cc grpc.ClientConnInterface) GameServersClient {
	return &gameServersClient{cc}
}

func (c *gameServersClient) Updates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GameServer, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameServers_ServiceDesc.Streams[0], GameServers_Updates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GameServer, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServers_UpdatesClient = grpc.ClientStreamingClient[GameServer, emptypb.Empty]

func (c *gameServersClient) Withdraw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GameServers_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServersServer is the server API for GameServers service.
// All implementations must embed UnimplementedGameServersServer
// for forward compatibility.
type GameServersServer interface {
	Updates(grpc.ClientStreamingServer[GameServer, emptypb.Empty]) error
	Withdraw(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedGameServersServer()
}

// UnimplementedGameServersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServersServer struct{}

func (UnimplementedGameServersServer) Updates(grpc.ClientStreamingServer[GameServer, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Updates not implemented")
}
func (UnimplementedGameServersServer) Withdraw(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedGameServersServer) mustEmbedUnimplementedGameServersServer() {}
func (UnimplementedGameServersServer) testEmbeddedByValue()                     {}

// UnsafeGameServersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServersServer will
// result in compilation errors.
type UnsafeGameServersServer interface {
	mustEmbedUnimplementedGameServersServer()
}

func RegisterGameServersServer(s grpc.ServiceRegistrar, srv GameServersServer) {
	// If the following call pancis, it indicates UnimplementedGameServersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameServers_ServiceDesc, srv)
}

func _GameServers_Updates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServersServer).Updates(&grpc.GenericServerStream[GameServer, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServers_UpdatesServer = grpc.ClientStreamingServer[GameServer, emptypb.Empty]

func _GameServers_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServersServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameServers_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServersServer).Withdraw(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GameServers_ServiceDesc is the grpc.ServiceDesc for GameServers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectile.GameServers",
	HandlerType: (*GameServersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Withdraw",
			Handler:    _GameServers_Withdraw_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Updates",
			Handler:       _GameServers_Updates_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agentmsg.proto",
}
